### ISSUE TITLE
Workflow unable to find the issue

### ISSUE THREAD

**Issue by marcofranssen** [peter-evans/find-comment#137]
I have following steps in my workflow. Repeated runs of the workflow does NOT update the existing comment but always creates new comments. 

Assumption based on docs `body-includes` matches if a part of the string matches.

```yaml
      - name: Find Validation Comment
        uses: peter-evans/find-comment@v2.3.0
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: github-actions
          body-includes: We have successfully validated your inputs

      - name: Validation comment
        uses: peter-evans/create-or-update-comment@v2.1.1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            We have successfully validated your inputs and proceed with account creation…
```
