### ISSUE TITLE
Comment author "github-actions" not recognized as author

### ISSUE THREAD

**Issue by samuelT2** [peter-evans/find-comment#171]
Hi

Thank you very much for this action - I just started to use it within a workflow. One thing I noticed is that "comment-author" for the author "github-actions" is not working.

My workflow starts like this:

```
on:
  issues:
    types: [closed]

jobs:
  close-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2.4.0
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-author: github-actions
        body-includes: Kimai activity created, ID-
```
My comment looks like this:
![image](https://user-images.githubusercontent.com/10983143/234524587-9eb5b2dc-0cab-4cf9-9cf5-2981a6090b6d.png)

It works fine when i only use "body-includes" - but when I want to further restrict it to the author "github-actions" it's not working anymore. Any hints or thoughts from your end?
