### ISSUE TITLE
Always fails with error `Not Found`

### ISSUE THREAD

**Issue by troykelly** [peter-evans/find-comment#172]
### Config

```yaml
      - name: 🔎 Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: OctoDNS Plan
```

### Error

```text
Run peter-evans/find-comment@v2
  with:
    body-includes: OctoDNS Plan
    token: ***
    repository: xxx/yyy
    direction: first
    nth: 0
Error: Not Found
```

### Troubleshooting

I've tried setting a token using `GITHUB_TOKEN` and a `PAT`, and not - nothing seems to work.
