### ISSUE TITLE
finding comment on a merged pull request

### ISSUE THREAD

**Issue by p-costa** [peter-evans/find-comment#26]
Hi @peter-evans ,

I am trying to find a comment located on a merged and closed pull request. Can I achieve this with `find-comment`? I tried something like shown below but it does not do the job. 

```yaml
 on:
   pull_request:
     types: [closed]
 env:
   TWEET_KEYWORD: '__[tweet]__'
 
 jobs:
   publish_tweet:
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged
     steps:
     - name: find the tweet comment matching the keyword env.TWEET_KEYWORD
       uses: peter-evans/find-comment@v1
       id: fc
       with:
         issue-number: ${{ github.event.pull_request.number }}
         comment-author: github-actions[bot]
         body-includes: ${{ env.TWEET_KEYWORD }}
```
