### ISSUE TITLE
Output the comment's author

### ISSUE THREAD

**Issue by quinnturner** [peter-evans/find-comment#48]
Thank you for creating this package!

For completeness, I think one of the outputs should be the `comment-author`. In my use case, I am trying to ensure that the most recent comment with some text is _not_ a specific author (a bot, in my case). It's not clear whether this is possible to determine without outputting the comment author.

Example of my use case:

```yaml
      - name: Find /deploy in PR (if applicable)
        uses: peter-evans/find-comment@v1
        if: ${{ github.event.client_payload.slash_command.args.named.pr_number }}
        id: fc
        with:
          issue-number: ${{ github.event.client_payload.slash_command.args.named.pr_number }}
          body-includes: /deploy
          direction: last

      - name: Check whether we need to deploy (/deploy, if applicable)
        if: ${{ github.event.client_payload.slash_command.args.named.pr_number }} && ${{ steps.fc.outputs.comment-id }} != 0 && ${{ steps.fc.outputs.comment-author }} != 'github-action[bot]'
        run: ...
```
