### ISSUE TITLE
Bot comments

### ISSUE THREAD

**Issue by dmitry-engineer** [peter-evans/find-comment#52]
I try to find comments by github-action bot but can't Receive empty outputs

**Comment by dmitry-engineer** [comment]
```
- name: Find Comment
  uses: peter-evans/find-comment@v1
  continue-on-error: true
  id: fc
  with:
    issue-number: ${{ github.event.pull_request.number }}
    comment-author: 'github-actions[bot]'
    direction: last
- run: |
    echo "${{ steps.fc.outputs.comment-id }}"
```
