### ISSUE TITLE
Find comment by id

### ISSUE THREAD

**Issue by plazum** [peter-evans/find-comment#58]
Thank you for the wonderful action, it helps me a lot!
Currently I use it to fetch the body of a comment to be used in my workflow, but I find that I can't get the comment by comment id.
Would you please add the feature so that I can get a comment by comment id?

**Comment by peter-evans** [comment]
Hi @plazum 

The point of this action is to find the comment ID of a comment that you only know other details about. If you already know the comment ID then you can just use it to get the body.

For example, you can use [github-script](https://github.com/actions/github-script). I haven't tested the following steps, but something close to this should work.

```yml
      - uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.my-step.outputs.comment-id }}
            }).body
          result-encoding: string

      - run: echo "${{ steps.get-comment.outputs.result }}"
```

**Comment by plazum** [comment]
Hi @peter-evans, thank you for you kindly reply.
The code you give will work with a little modification as follows:
```yaml
      - uses: actions/github-script@v5
        id: get-comment
        with:
          script: |
            return (await github.rest.issues.getComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: ${{ steps.my-step.outputs.comment-id }}
            })).data.body;
          result-encoding: string
```
