### ISSUE TITLE
`Not found` error when using container 

### ISSUE THREAD

**Issue by tlsvda** [peter-evans/find-comment#61]
When using this action with this configuration:
```
name: Comment translation list
on: push

jobs:
  translations:
    runs-on: ubuntu-latest
    container:
      image: leviy/build-image
    steps:
      - name: Find comment with added translation keys
        uses: peter-evans/find-comment@v1
        id: findComment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: New added translation keys

```
We are using this docker image: https://hub.docker.com/r/leviy/build-image

It fails with this error:
```
Run peter-evans/find-comment@v1
/usr/bin/docker exec  b2e6705e275dc30ba9e27b1ee7700ff5c555983034fb2f2dd3fbfdad957083ac sh -c "cat /etc/*release | grep ^ID"
Error: Not Found
```

We don't have this with other actions, for example this one: [necojackarc/auto-request-review](https://github.com/necojackarc/auto-request-review)
