### ISSUE TITLE
Error: Not Found with PAT generated

### ISSUE THREAD

**Issue by pranayagra** [peter-evans/find-comment#90]
I am trying to use this action in my private repo. I generated a PAT, added it to my GitHub repo -> action -> secret with the name TEST, and included the token in my .yaml file as follows:

```
name: TestPE
on: [workflow_dispatch, pull_request]
concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  test_private_action_job:
    name: TestingPE
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Build output
        token: ${{ secrets.TEST }}
```

However, when I run the workflow, I receive `Run peter-evans/find-comment@v2 Error: Not Found` on the `Find Comment` step. Please let me know what I am doing wrong.
